# Generated by Django 5.1 on 2024-09-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'verbose_name_plural': 'KYC'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
